name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install -g firebase-tools
        npm ci

    - name: Deploy to Firebase
      run: |
        firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{1//0hnCO-f_IaDMYCgYIARAAGBESNwF-L9Irv5ZTP0b_BfyuaKpFfwc8lXnBjmYJT24p3XiC29JTibnCrMoRjGxXf_pmCqrspD44MWE}}
